2023-09-14 16:42:09,715 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-14 16:42:30,172 ERROR: Exception on /editer_profil [POST] [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/flask/app.py:1745]
Traceback (most recent call last):
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1966, in _exec_single_context
    cursor, str_statement, effective_parameters, context
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: utilisateur.nom

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/routes.py", line 102, in editer_profil
    db.session.commit()
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 554, in commit
    return self._proxied.commit()
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 4315, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 645, in execute
    uow,
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 90, in save_obj
    update,
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 910, in _emit_update_statements
    statement, multiparams, execution_options=execution_options
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    execution_options or NO_OPTIONS,
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    self, distilled_params, execution_options
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1645, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    dialect, context, statement, parameters
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1985, in _exec_single_context
    e, str_statement, effective_parameters, cursor, context
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1966, in _exec_single_context
    cursor, str_statement, effective_parameters, context
  File "/home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: utilisateur.nom
[SQL: UPDATE utilisateur SET nom=? WHERE utilisateur.id = ?]
[parameters: ('Ron', 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-09-18 12:39:55,389 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 12:40:10,444 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 12:41:04,744 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 13:15:14,375 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 13:21:12,797 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 13:23:27,901 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:06:18,008 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:07:31,883 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:08:21,047 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:09:48,188 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:10:43,532 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:13:21,516 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:14:47,285 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:14:53,883 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:20:16,089 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:23:39,304 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
2023-09-18 14:43:30,923 INFO: Démarrage de petits Gazoullis [in /home/etudiant/Bureau/420-5PC/Laboratoires/Laboratoire00.1/app/__init__.py:43]
